name: cratch
description: The Future of Content Creation.

publish_to: "https://cratch.io" # Remove this line if you wish to publish to pub.dev

version: 1.1.7+17

environment:
  sdk: ">=2.19.6 <=3.1.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil:
  flutter_svg:
  cached_network_image:
  font_awesome_flutter:
  persistent_bottom_nav_bar:
  dependency_validator:
  flutter_zoom_drawer: ^3.0.4+1
  get: ^4.6.5
  package_info_plus:
  intl:
  provider:
  carousel_slider: ^4.2.1
  image_picker: ^0.8.5+3
  textfield_tags: ^2.0.2
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.0.3  # Replace with the latest version
  socket_io_client:
  video_player: 
  jwt_decoder:
  image:
  video_thumbnail:
  shimmer:
  flutter_ffmpeg:
  chewie: ^1.7.0
  timeago:
  freestyle_speed_dial:
  shared_preferences:
  dotted_border: ^2.0.0+3
  chart_sparkline: ^1.0.13
  walletconnect_flutter_v2: ^2.0.12
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf

